PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?countryLabel GROUP_CONCAT(UCASE(?languageLabel); separator="|") AS ?languageLabels
WHERE {
  ?country a dbo:Country .
  ?country rdfs:label ?countryLabel .
  FILTER (lang(?countryLabel) = "en") .
  FILTER (strstarts(str(?countryLabel), "A")) .
  {
    ?country dct:subject dbc:Countries_in_Europe .
  } UNION {
    ?country dct:subject dbc:Countries_in_North_America .
  }
  OPTIONAL {
    ?country dbo:officialLanguage ?language .
    ?language rdfs:label ?languageLabel .
    FILTER (lang(?languageLabel) = "en")
  }
}
ORDER BY ?countryLabel
