PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>

SELECT ?person ?birthCountry ?universityCountry
WHERE {
  ?person a dbo:Person .
  ?person dbo:award dbr:Nobel_Prize_in_Physics .
  ?person dbp:birthPlace ?birthPlace .
  ?birthPlace dbo:country ?birthCountry .
  ?person dbo:almaMater ?university .
  ?university dbo:country ?universityCountry .
  FILTER (?birthCountry != ?universityCountry)
}
